# Site settings
title: Diagoge
email: tm@diagoge.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mo-tom.github.io" # the base hostname & protocol for your site
twitter_username: mo_tom
github_username:  mo-tom

# Build settings
markdown: kramdown

plugins: _plugins

# gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# URL structure
permalink: none
